site_name: Relatório Técnico - VueJS
nav:
  - Home: index.md
  - Introdução: introducao.md
  - Componentes:
      - Visão Geral: componentes/visao-geral.md
      - Componentes Reutilizáveis: componentes/reutilizaveis.md
  - Diretivas: diretivas.md
  - Ferramentas e Bibliotecas Adicionais: ferramentas.md
  - Conclusão: conclusao.md
